library(dplyr)
library(randomForest)
library(mlr)
library(dplyr)
library(ranger)
library(tuneRanger)

df <- read.csv("../model2/dochody_i_ludnosc.csv", encoding = "UTF-8")
train <- read.csv("../model2/train.csv")
t2 <- train %>% left_join(df, by = c("id" = "Kod"))
t3 <- subset(t2, select = -c(X.x, gmina, powiat, id, longitude, latitude, X.y, Nazwa))
t3 <- na.omit(t3)

classif_task <- makeClassifTask(data = t3, target = "wynik", positive = 1)
classif_lrn <- makeLearner("classif.ranger", par.vals = list( "num.trees" = 2500), predict.type = "prob")
res_ranger <- tuneRanger(classif_task, measure = list(gmean), num.threads = 6, num.trees = 2500)
df_test <- na.omit(subset(df, select = -c(X, Kod)))
gminy <- df_test[,"Nazwa"]

df_test <- subset(df_test, select = -c(Nazwa))
pred_ranger <- predict(res_ranger$model, newdata = df_test)

result <- as.data.frame(cbind(as.numeric(pred_ranger$data$prob.1), gminy))

gm_miej <- c("Karpacz (1)",
             "Krynica Morska (1)",
             "Sucha Beskidzka (1)",
             "Z³otów (1)",
             "Pruszcz Gdañski (1)",
             "Lubawa (1)",
             "Bieruñ (1)",
             "£eba (1)",
             "¯ywiec (1)",
             "Mielec (1)",
             "Szczawno-Zdrój (1)",
             "Oœwiêcim (1)",
             "Kwidzyn (1)",
             "Wysokie Mazowieckie (1)",
             "Czarnków (1)",
             "Limanowa (1)",
             "Ustroñ (1)",
             "Kostrzyn nad Odr¹ (1)",
             "Duszniki-Zdrój (1)",
             "Zakopane (1)",
             "Œwidnica (1)",
             "£añcut (1)",
             "Sanok (1)",
             "Pu³awy (1)",
             "Stalowa Wola (1)",
             "Podkowa Leœna (1)",
             "Cieszyn (1)",
             "Wêgrów (1)",
             "Ostrów Wielkopolski (1)",
             "Garwolin (1)",
             "O³awa (1)",
             "Jastarnia (1)",
             "Pruszków (1)",
             "Turek (1)",
             "Puszczykowo (1)",
             "Miko³ów (1)",
             "Bi³goraj (1)",
             "Jas³o (1)",
             "Ko³o (1)",
             "Jaros³aw (1)",
             "Pi³a (1)",
             "Ko³obrzeg (1)",
             "Cz³uchów (1)",
             "Tomaszów Lubelski (1)",
             "Brodnica (1)",
             "Sandomierz (1)",
             "Boles³awiec (1)",
             "¯ary (1)",
             "Kutno (1)",
             "S³upca (1)",
             "Bochnia (1)",
             "M³awa (1)",
             "W¹growiec (1)",
             "Dêbica (1)",
             "Lubliniec (1)",
             "Le¿ajsk (1)",
             "Starachowice (1)",
             "P³oñsk (1)",
             "Ciechanów (1)",
             "K³odzko (1)",
             "Lubin (1)",
             "Gorlice (1)",
             "Ciechocinek (1)",
             "Nowy Targ (1)",
             "Koœcian (1)",
             "Rawa Mazowiecka (1)",
             "£uków (1)",
             "Dzier¿oniów (1)",
             "Radomsko (1)",
             "Sierpc (1)",
             "G³ogów (1)",
             "Soko³ów Podlaski (1)",
             "Tczew (1)",
             "Kêdzierzyn-KoŸle (1)",
             "Ostrów Mazowiecka (1)",
             "Œwieradów-Zdrój (1)",
             "Lubartów (1)",
             "Gniezno (1)",
             "I³awa (1)",
             "Racibórz (1)",
             "Polanica-Zdrój (1)",
             "Rypin (1)",
             "Ostróda (1)",
             "Miñsk Mazowiecki (1)",
             "Przeworsk (1)",
             "Dzia³dowo (1)",
             "Nowa Sól (1)",
             "Puck (1)",
             "Radziejów (1)",
             "Tarnowskie Góry (1)",
             "£owicz (1)",
             "Skórcz (1)",
             "Marki (1)",
             "Nowy Dwór Mazowiecki (1)",
             "Józefów (1)",
             "Szczecinek (1)",
             "Bielsk Podlaski (1)",
             "Zgorzelec (1)",
             "Zielonka (1)",
             "Starogard Gdañski (1)",
             "Koœcierzyna (1)",
             "Bukowno (1)",
             "Radzyñ Podlaski (1)",
             "Przasnysz (1)",
             "Wejherowo (1)",
             "Chojnice (1)",
             "Mr¹gowo (1)",
             "Szczytno (1)",
             "Stoczek £ukowski (1)",
             "Zduñska Wola (1)",
             "£êczyca (1)",
             "Sieradz (1)",
             "Lêbork (1)",
             "Tomaszów Mazowiecki (1)",
             "Konstantynów £ódzki (1)",
             "Chodzie¿ (1)",
             "£aziska Górne (1)",
             "Oleœnica (1)",
             "Szklarska Porêba (1)",
             "Lubaczów (1)",
             "Lêdziny (1)",
             "Radlin (1)",
             "Zawiercie (1)",
             "Be³chatów (1)",
             "Stargard (1)",
             "Sochaczew (1)",
             "Wa³cz (1)",
             "Krasnystaw (1)",
             "S³awno (1)",
             "Lidzbark Warmiñski (1)",
             "Otwock (1)",
             "W¹brzeŸno (1)",
             "Augustów (1)",
             "Nowe Miasto Lubawskie (1)",
             "Lubañ (1)",
             "Radzionków (1)",
             "Sulejówek (1)",
             "Knurów (1)",
             "Brzeg (1)",
             "Z¹bki (1)",
             "Terespol (1)",
             "Bêdzin (1)",
             "CzeladŸ (1)",
             "Legionowo (1)",
             "Maków Mazowiecki (1)",
             "Kêtrzyn (1)",
             "Miasteczko Œl¹skie (1)",
             "Piastów (1)",
             "Mszana Dolna (1)",
             "Inowroc³aw (1)",
             "Z³otoryja (1)",
             "Malbork (1)",
             "Pabianice (1)",
             "Œwidwin (1)",
             "Wodzis³aw Œl¹ski (1)",
             "Skar¿ysko-Kamienna (1)",
             "Gi¿ycko (1)",
             "Lipno (1)",
             "Jawor (1)",
             "E³k (1)",
             "Luboñ (1)",
             "Ostrowiec Œwiêtokrzyski (1)",
             "Gostynin (1)",
             "Siemiatycze (1)",
             "Kamienna Góra (1)",
             "Hrubieszów (1)",
             "¯agañ (1)",
             "Piechowice (1)",
             "Hajnówka (1)",
             "Rydu³towy (1)",
             "Ustka (1)",
             "Kraœnik (1)",
             "Zgierz (1)",
             "Pyskowice (1)",
             "Œwidnik (1)",
             "Braniewo (1)",
             "Golub-Dobrzyñ (1)",
             "Milanówek (1)",
             "Bartoszyce (1)",
             "Bia³ogard (1)",
             "Rumia (1)",
             "Jordanów (1)",
             "Zambrów (1)",
             "Koby³ka (1)",
             "¯yrardów (1)",
             "Szczyrk (1)",
             "£êknica (1)",
             "Œwiebodzice (1)",
             "S³awków (1)",
             "Bielawa (1)",
             "Imielin (1)",
             "Grajewo (1)",
             "Myszków (1)",
             "Wis³a (1)",
             "Che³mno (1)",
             "Zawidów (1)",
             "Aleksandrów Kujawski (1)",
             "Ozorków (1)",
             "Gubin (1)",
             "Brañsk (1)",
             "Kowal (1)",
             "Kudowa-Zdrój (1)",
             "Pionki (1)",
             "Chojnów (1)",
             "Brzeziny (1)",
             "Kolno (1)",
             "W³odawa (1)",
             "Dêblin (1)",
             "Raci¹¿ (1)",
             "Miêdzyrzec Podlaski (1)",
             "Nowa Ruda (1)",
             "Dar³owo (1)",
             "Reda (1)",
             "Hel (1)",
             "Wojkowice (1)",
             "G³owno (1)",
             "Obrzycko (1)",
             "Górowo I³aweckie (1)",
             "Radymno (1)",
             "Sejny (1)",
             "Kowary (1)",
             "Orzesze (1)",
             "Sulmierzyce (1)",
             "Jedlina-Zdrój (1)",
             "Che³m¿a (1)",
             "Gozdnica (1)",
             "Grybów (1)",
             "£askarzew (1)",
             "Dynów (1)",
             "Kalety (1)",
             "Pi³awa Górna (1)",
             "Pszów (1)",
             "Wojcieszów (1)",
             "Boguszów-Gorce (1)",
             "Nieszawa (1)",
             "Porêba (1)",
             "Rejowiec Fabryczny (1)"
)

indexes <- 1:237
info <- cbind(gm_miej, indexes)

info <- info %>% as.data.frame() %>% left_join(result, by = c("gm_miej" = "gminy"))
colnames(info) = c("gm_miej", "id", "score")
info <- info[order(info$score, decreasing=TRUE),]
info <- cbind(info, 1:237)
rownames(info) <- NULL
colnames(info) = c("gm_miej", "theirScore", "score", "ourScore")

info$diff <- abs(as.numeric(info$ourScore) - as.numeric(info$theirScore))
info$isGood <- ifelse(info$diff <= 60, 1, 0)

cat("Percent of \"well calculated\":", mean(info$isGood) * 100, "%")
cat("Mean difference between our place in ranking and WUT's experts:", mean(info$diff))
print("Summary of diff output column")
summary(info$diff)
