library(dplyr)
library(randomForest)
library(mlr)
library(ranger)
library(tuneRanger)

dt <- read.csv("../model2/dochody_i_ludnosc.csv", encoding = "UTF-8")
train <- read.csv("../model2/train.csv")
t2 <- train %>% left_join(dt, by=c("id" = "Kod"))
t3 <- subset(t2, select = -c(X.x, gmina, powiat, id, longitude, latitude, X.y, Nazwa))
t3 <- na.omit(t3)


classif_task <- makeClassifTask(data = t3, target = "wynik", positive = 1)
classif_lrn <- makeLearner("classif.ranger", par.vals = list( "num.trees" = 2500), predict.type = "prob")
res_ranger <- tuneRanger(classif_task, measure = list(gmean), num.threads = 6, num.trees = 2500)
dt_test <- na.omit(subset(dt, select = -c(X, Kod)))
gminy <- dt_test[,"Nazwa"]

dt_test <- subset(dt_test, select = -c(Nazwa))
pred_ranger <- predict(res_ranger$model, newdata = dt_test)

#rg <- ranger(wynik~., data=t3)

#getLearnerProperties(classif_lrn)
#importance(rg)

#pred <- predict(rg, dt_test)
#result2 <- as.data.frame(cbind(pred$predictions,gminy))

result <- as.data.frame(cbind(as.numeric(pred_ranger$data$prob.1),gminy))

gm_miej_wiej <- c("Polkowice (3)"
,"Ożarów Mazowiecki (3)"
,"Stryków (3)"
,"Kórnik (3)"
,"Błonie (3)"
,"Nowe Skalmierzyce (3)"
,"Zbąszynek (3)"
,"Międzyzdroje (3)"
,"Dziwnów (3)"
,"Swarzędz (3)"
,"Goleniów (3)"
,"Rzgów (3)"
,"Kąty Wrocławskie (3)"
,"Łomianki (3)"
,"Niepołomice (3)"
,"Nowy Tomyśl (3)"
,"Jelcz-Laskowice (3)"
,"Wronki (3)"
,"Piaseczno (3)"
,"Gostyń (3)"
,"Połaniec (3)"
,"Środa Śląska (3)"
,"Wolsztyn (3)"
,"Solec Kujawski (3)"
,"Słubice (3)"
,"Świecie (3)"
,"Grodzisk Mazowiecki (3)"
,"Grodzisk Wielkopolski (3)"
,"Wieruszów (3)"
,"Kępno (3)"
,"Buk (3)"
,"Krapkowice (3)"
,"Wieluń (3)"
,"Grójec (3)"
,"Siechnice (3)"
,"Czechowice-Dziedzice (3)"
,"Mikołajki (3)"
,"Siewierz (3)"
,"Babimost (3)"
,"Wyszków (3)"
,"Brzeg Dolny (3)"
,"Konstancin-Jeziorna (3)"
,"Skawina (3)"
,"Władysławowo (3)"
,"Mszczonów (3)"
,"Jarocin (3)"
,"Środa Wielkopolska (3)"
,"Świebodzin (3)"
,"Stęszew (3)"
,"Supraśl (3)"
,"Nysa (3)"
,"Rawicz (3)"
,"Żarów (3)"
,"Śrem (3)"
,"Bytów (3)"
,"Bogatynia (3)"
,"Kleczew (3)"
,"Twardogóra (3)"
,"Wadowice (3)"
,"Kozienice (3)"
,"Gościno (3)"
,"Różan (3)"
,"Krotoszyn (3)"
,"Szamotuły (3)"
,"Września (3)"
,"Oborniki (3)"
,"Skoczów (3)"
,"Myślenice (3)"
,"Police (3)"
,"Murowana Goślina (3)"
,"Brwinów (3)"
,"Ostrzeszów (3)"
," "
,"Strzegom (3)"
,"Krynica-Zdrój (3)"
,"Opalenica (3)"
,"Pniewy (3)"
,"Gogolin (3)"
,"Żukowo (3)"
,"Działoszyn (3)"
,"Czyżew (3)"
,"Kłobuck (3)"
,"Busko-Zdrój (3)"
,"Chrzanów (3)"
,"Barlinek (3)"
,"Nekla (3)"
,"Radzymin (3)"
,"Strzelce Opolskie (3)"
,"Nidzica (3)"
,"Olecko (3)"
,"Rydzyna (3)"
,"Karczew (3)"
,"Włoszczowa (3)"
,"Kostrzyn (3)"
,"Międzychód (3)"
,"Głogów Małopolski (3)"
,"Miechów (3)"
,"Ząbkowice Śląskie (3)"
,"Końskie (3)"
,"Sztum (3)"
,"Olesno (3)"
,"Aleksandrów Łódzki (3)"
,"Pleszew (3)"
,"Brzeszcze (3)"
,"Gryfino (3)"
,"Śmigiel (3)"
,"Kargowa (3)"
,"Namysłów (3)"
,"Czarna Woda (3)"
,"Kartuzy (3)"
,"Góra Kalwaria (3)"
,"Nowa Dęba (3)"
,"Sulęcin (3)"
,"Drawsko Pomorskie (3)"
,"Dębno (3)"
,"Kluczbork (3)"
,"Pszczyna (3)"
,"Wołomin (3)"
,"Trzebnica (3)"
,"Janów Lubelski (3)"
,"Rzepin (3)"
,"Dobczyce (3)"
,"Kazimierz Dolny (3)"
,"Białobrzegi (3)"
,"Osieczna (3)"
,"Strzelin (3)"
,"Choroszcz (3)"
,"Zwierzyniec (3)"
,"Pobiedziska (3)"
,"Krosno Odrzańskie (3)"
,"Opoczno (3)"
,"Wolbrom (3)"
,"Tuchola (3)"
,"Wolbórz (3)"
,"Nakło nad Notecią (3)"
,"Krzepice (3)"
,"Trzebinia (3)"
,"Krobia (3)"
,"Krzyż Wielkopolski (3)"
,"Olsztynek (3)"
,"Staszów (3)"
,"Olkusz (3)"
,"Zator (3)"
,"Głubczyce (3)"
,"Andrychów (3)"
,"Łęczna (3)"
,"Zdzieszowice (3)"
,"Koluszki (3)"
,"Ozimek (3)"
,"Wieliczka (3)"
,"Chełmek (3)"
,"Milicz (3)"
,"Szczawnica (3)"
,"Mosina (3)"
,"Czempiń (3)"
,"Czerwieńsk (3)"
,"Rabka-Zdrój (3)"
,"Kowalewo Pomorskie (3)"
,"Tarczyn (3)"
,"Sulechów (3)"
,"Łosice (3)"
,"Czaplinek (3)"
,"Margonin (3)"
,"Karlino (3)"
,"Trzcianka (3)"
,"Sokółka (3)"
,"Iwonicz-Zdrój (3)"
,"Mikstat (3)"
,"Praszka (3)"
,"Czarne (3)"
,"Parczew (3)"
,"Strzelce Krajeńskie (3)"
,"Sobótka (3)"
,"Łask (3)"
,"Skwierzyna (3)"
,"Prochowice (3)"
,"Ujazd (3)"
,"Zawadzkie (3)"
,"Sośnicowice (3)"
,"Pińczów (3)"
,"Żnin (3)"
,"Serock (3)"
,"Kęty (3)"
,"Gryfice (3)"
,"Nowogard (3)"
,"Kamień Pomorski (3)"
,"Lubsko (3)"
,"Libiąż (3)"
,"Prudnik (3)"
,"Pułtusk (3)"
,"Zbąszyń (3)"
,"Krzeszowice (3)"
,"Stronie Śląskie (3)"
,"Kolonowskie (3)"
,"Lipsko (3)"
,"Pyrzyce (3)"
,"Wołów (3)"
,"Stepnica (3)"
,"Trzemeszno (3)"
,"Rogoźno (3)"
,"Mogilno (3)"
,"Grodków (3)"
,"Bytom Odrzański (3)"
,"Brzesko (3)"
,"Sieraków (3)"
,"Rakoniewice (3)"
,"Kłecko (3)"
,"Syców (3)"
,"Ujście (3)"
,"Pilawa (3)"
,"Nałęczów (3)"
,"Krajenka (3)"
,"Barcin (3)"
,"Janikowo (3)"
,"Gołdap (3)"
,"Łobez (3)"
,"Jabłonowo Pomorskie (3)"
,"Drezdenko (3)"
,"Kolbuszowa (3)"
,"Gniewkowo (3)"
,"Myślibórz (3)"
,"Mirosławiec (3)"
,"Choszczno (3)"
,"Dobrodzień (3)"
,"Kalisz Pomorski (3)"
,"Jędrzejów (3)"
,"Lesko (3)"
,"Skoki (3)"
,"Kamieńsk (3)"
,"Lwówek Śląski (3)"
,"Wasilków (3)"
,"Nisko (3)"
,"Dobre Miasto (3)"
,"Oborniki Śląskie (3)"
,"Miastko (3)"
,"Iłowa (3)"
,"Kruszwica (3)"
,"Wschowa (3)"
,"Susz (3)"
,"Głuchołazy (3)"
,"Prószków (3)"
,"Boguchwała (3)"
,"Szprotawa (3)"
,"Lubawka (3)"
,"Trzebiatów (3)"
,"Radków (3)"
,"Połczyn-Zdrój (3)"
,"Ryn (3)"
,"Koźmin Wielkopolski (3)"
,"Żuromin (3)"
,"Mieroszów (3)"
,"Sława (3)"
,"Tuszyn (3)"
,"Gryfów Śląski (3)"
,"Sępólno Krajeńskie (3)"
,"Tyczyn (3)"
,"Dobrzyca (3)"
,"Odolanów (3)"
,"Kalwaria Zebrzydowska (3)"
,"Olszyna (3)"
,"Pilica (3)"
,"Niemodlin (3)"
,"Czersk (3)"
,"Ogrodzieniec (3)"
,"Świątniki Górne (3)"
,"Pisz (3)"
,"Dąbrowa Tarnowska (3)"
,"Halinów (3)"
,"Dobra (3)"
,"Skarszewy (3)"
,"Mogielnica (3)"
,"Głogówek (3)"
,"Nowogrodziec (3)"
,"Ośno Lubuskie (3)"
,"Morąg (3)"
,"Czarna Białostocka (3)"
,"Miłosław (3)"
,"Pajęczno (3)"
,"Pasłęk (3)"
,"Sędziszów Małopolski (3)"
,"Warka (3)"
,"Opatów (3)"
,"Międzybórz (3)"
,"Sędziszów (3)"
,"Prabuty (3)"
,"Łapy (3)"
,"Ropczyce (3)"
,"Grabów nad Prosną (3)"
,"Lubniewice (3)"
,"Żabno (3)"
,"Barczewo (3)"
,"Witnica (3)"
,"Lądek-Zdrój (3)"
,"Dzierzgoń (3)"
,"Pelplin (3)"
,"Koronowo (3)"
,"Brześć Kujawski (3)"
,"Okonek (3)"
,"Złocieniec (3)"
,"Brusy (3)"
,"Jastrowie (3)"
,"Góra (3)"
,"Sieniawa (3)"
,"Muszyna (3)"
,"Jutrosin (3)"
,"Rymanów (3)"
,"Lwówek (3)"
,"Przysucha (3)"
,"Pieńsk (3)"
,"Cedynia (3)"
,"Poddębice (3)"
,"Oleszyce (3)"
,"Wysoka (3)"
,"Tuczno (3)"
,"Sianów (3)"
,"Ruciane-Nida (3)"
,"Zduny (3)"
,"Ślesin (3)"
,"Zwoleń (3)"
,"Czerniejewo (3)"
,"Ustrzyki Dolne (3)"
,"Chocianów (3)"
,"Woźniki (3)"
,"Ścinawa (3)"
,"Nowy Dwór Gdański (3)"
,"Borek Wielkopolski (3)"
,"Niemcza (3)"
,"Borne Sulinowo (3)"
,"Cybinka (3)"
,"Nowogród Bobrzański (3)"
,"Nowe Miasto nad Pilicą (3)"
,"Blachownia (3)"
,"Żerków (3)"
,"Ożarów (3)"
,"Wilamowice (3)"
,"Prusice (3)"
,"Kępice (3)"
,"Łasin (3)"
,"Cieszanów (3)"
,"Bojanowo (3)"
,"Szamocin (3)"
,"Chęciny (3)"
,"Dobiegniew (3)"
,"Drzewica (3)"
,"Skała (3)"
,"Żelechów (3)"
,"Zakroczym (3)"
,"Bobolice (3)"
,"Ryki (3)"
,"Sokołów Małopolski (3)"
,"Tychowo (3)"
,"Toszek (3)"
,"Żychlin (3)"
,"Lidzbark (3)"
,"Sułkowice (3)"
,"Poniatowa (3)"
,"Gniew (3)"
,"Chojna (3)"
,"Bardo (3)"
,"Strzelno (3)"
,"Leśnica (3)"
,"Węgorzewo (3)"
,"Nasielsk (3)"
,"Biskupiec (3)"
,"Opole Lubelskie (3)"
,"Resko (3)"
,"Sompolno (3)"
,"Bystrzyca Kłodzka (3)"
,"Miejska Górka (3)"
,"Więcbork (3)"
,"Lipiany (3)"
,"Tolkmicko (3)"
,"Zalewo (3)"
,"Wyrzysk (3)"
,"Bierutów (3)"
,"Dolsk (3)"
,"Szydłowiec (3)"
,"Witkowo (3)"
,"Otmuchów (3)"
,"Żarki (3)"
,"Mońki (3)"
,"Zaklików (3)"
,"Pogorzela (3)"
,"Suchedniów (3)"
,"Poniec (3)"
,"Mrocza (3)"
,"Proszowice (3)"
,"Torzym (3)"
,"Żmigród (3)"
,"Baborów (3)"
,"Czerwionka-Leszczyny (3)"
,"Golczewo (3)"
,"Strumień (3)"
,"Raszków (3)"
,"Jedlicze (3)"
,"Polanów (3)"
,"Dobrzany (3)"
,"Kałuszyn (3)"
,"Glinojeck (3)"
,"Uniejów (3)"
,"Drawno (3)"
,"Orneta (3)"
,"Węgliniec (3)"
,"Nowe Warpno (3)"
,"Jaworzyna Śląska (3)"
,"Chodecz (3)"
,"Strzyżów (3)"
,"Pełczyce (3)"
,"Stopnica (3)"
,"Lubień Kujawski (3)"
,"Kuźnia Raciborska (3)"
,"Ulanów (3)"
,"Bełżyce (3)"
,"Gorzów Śląski (3)"
,"Złoty Stok (3)"
,"Kożuchów (3)"
,"Wieleń (3)"
,"Szubin (3)"
,"Nowe (3)"
,"Słomniki (3)"
,"Stary Sącz (3)"
,"Nowe Miasteczko (3)"
,"Książ Wielkopolski (3)"
,"Daleszyce (3)"
,"Głuszyca (3)"
,"Małogoszcz (3)"
,"Radzyń Chełmiński (3)"
,"Paczków (3)"
,"Trzciel (3)"
,"Krzywiń (3)"
,"Mieszkowice (3)"
,"Gołańcz (3)"
,"Kłodawa (3)"
,"Lewin Brzeski (3)"
,"Szlichtyngowa (3)"
,"Przedbórz (3)"
,"Przemków (3)"
,"Chociwel (3)"
,"Trzcińsko-Zdrój (3)"
,"Alwernia (3)"
,"Maków Podhalański (3)"
,"Wąchock (3)"
,"Recz (3)"
,"Frombork (3)"
,"Płoty (3)"
,"Kamień Krajeński (3)"
,"Krośniewice (3)"
,"Ziębice (3)"
,"Jaraczewo (3)"
,"Rudnik nad Sanem (3)"
,"Pilzno (3)"
,"Debrzno (3)"
,"Koniecpol (3)"
,"Chmielnik (3)"
,"Wolin (3)"
,"Narol (3)"
,"Zabłudów (3)"
,"Nowy Staw (3)"
,"Bychawa (3)"
,"Szczuczyn (3)"
,"Wołczyn (3)"
,"Pyzdry (3)"
,"Stawiszyn (3)"
,"Pieszyce (3)"
,"Łobżenica (3)"
,"Wielichowo (3)"
,"Zagórz (3)"
,"Ostrów Lubelski (3)"
,"Janowiec Wielkopolski (3)"
,"Łazy (3)"
,"Małomice (3)"
,"Kietrz (3)"
,"Pakość (3)"
,"Przedecz (3)"
,"Łabiszyn (3)"
,"Miłomłyn (3)"
,"Szepietowo (3)"
,"Reszel (3)"
,"Jasień (3)"
,"Nowa Sarzyna (3)"
,"Myszyniec (3)"
,"Górzno (3)"
,"Tarnogród (3)"
,"Kobylin (3)"
,"Michałowo (3)"
,"Biały Bór (3)"
,"Koziegłowy (3)"
,"Kleszczele (3)"
,"Człopa (3)"
,"Szczekociny (3)"
,"Piotrków Kujawski (3)"
,"Brzozów (3)"
,"Zagórów (3)"
,"Biała Rawska (3)"
,"Ostroróg (3)"
,"Orzysz (3)"
,"Kunów (3)"
,"Piwniczna-Zdrój (3)"
,"Lubraniec (3)"
,"Tuchów (3)"
,"Iłża (3)"
,"Łochów (3)"
,"Golina (3)"
,"Wyszogród (3)"
,"Skępe (3)"
,"Drobin (3)"
,"Węgorzyno (3)"
,"Kisielice (3)"
,"Byczyna (3)"
,"Drohiczyn (3)"
,"Krasnobród (3)"
,"Radomyśl Wielki (3)"
,"Baranów Sandomierski (3)"
,"Mrozy (3)"
,"Młynary (3)"
,"Barwice (3)"
,"Gąbin (3)"
,"Ćmielów (3)"
,"Moryń (3)"
,"Kańczuga (3)"
,"Kazimierza Wielka (3)"
,"Zelów (3)"
,"Józefów (3)"
,"Leśna (3)"
,"Łaszczów (3)"
,"Skaryszew (3)"
,"Knyszyn (3)"
,"Szczytna (3)"
,"Kosów Lacki (3)"
,"Wojnicz (3)"
,"Przecław (3)"
,"Ińsko (3)"
,"Nowy Wiśnicz (3)"
,"Zakliczyn (3)"
,"Ciechanowiec (3)"
,"Piaski (3)"
,"Sulejów (3)"
,"Wiązów (3)"
,"Stąporków (3)"
,"Rajgród (3)"
,"Pasym (3)"
,"Szczebrzeszyn (3)"
,"Krzanowice (3)"
,"Kock (3)"
,"Ciężkowice (3)"
,"Szadek (3)"
,"Biecz (3)"
,"Bolków (3)"
,"Chorzele (3)"
,"Kołaczyce (3)"
,"Suchań (3)"
,"Złoczew (3)"
,"Korfantów (3)"
,"Chocz (3)"
,"Warta (3)"
,"Mirsk (3)"
,"Maszewo (3)"
,"Wleń (3)"
,"Dąbrowa Białostocka (3)"
,"Dukla (3)"
,"Biała (3)"
,"Czchów (3)"
,"Suraż (3)"
,"Jeziorany (3)"
,"Radłów (3)"
,"Skalbmierz (3)"
,"Wąsosz (3)"
,"Tuliszków (3)"
,"Pieniężno (3)"
,"Koprzywnica (3)"
,"Tyszowce (3)"
,"Międzylesie (3)"
,"Miłakowo (3)"
,"Bisztynek (3)"
,"Dobra (3)"
,"Dąbie (3)"
,"Błaszki (3)"
,"Tykocin (3)"
,"Bobowa (3)"
,"Korsze (3)"
,"Kcynia (3)"
,"Biała Piska (3)"
,"Lubycza Królewska (3)"
,"Krynki (3)"
,"Błażowa (3)"
,"Nowe Brzesko (3)"
,"Rychwał (3)"
,"Pruchnik (3)"
,"Stawiski (3)"
,"Zawichost (3)"
,"Osiek (3)"
,"Bodzentyn (3)"
,"Mordy (3)"
,"Izbica Kujawska (3)"
,"Szczucin (3)"
,"Modliborzyce (3)"
,"Tłuszcz (3)"
,"Bieżuń (3)"
,"Suchowola (3)"
,"Urzędów (3)"
,"Brok (3)"
,"Świerzawa (3)"
,"Działoszyce (3)"
,"Siedliszcze (3)"
,"Goniądz (3)"
,"Annopol (3)"
,"Brzostek (3)"
,"Nowogród (3)"
,"Jedwabne (3)"
,"Frampol (3)"
,"Wyśmierzyce (3)"
,"Lubomierz (3)"
,"Dobrzyń nad Wisłą (3)"
,"Sępopol (3)"
,"Ryglice (3)"
,"Lipsk (3)")
nb <- 1:616
info <- cbind(gm_miej_wiej, nb)
library(dplyr)
info <- info %>% as.data.frame() %>% left_join(result, by=c("gm_miej_wiej" = "gminy"))

info <- info[order(info$V1, decreasing=TRUE),]
info <- cbind(info,0)
info <- cbind(info, 1:616)
#wersja 1
#info$`0`[1:100] <- ifelse(as.numeric(info$nb) <= 250, "Ok", "NieOk")[1:100] 
#info$`0`[101:200] <- ifelse(as.numeric(info$nb) <= 350, "Ok", "NieOk")[101:200]
#info$`0`[201:300] <- ifelse((as.numeric(info$nb) >= 150) & (as.numeric(info$nb) <= 450), "Ok", "NieOk")[201:300]
#info$`0`[301:400] <- ifelse((as.numeric(info$nb) >= 250) & (as.numeric(info$nb) <= 550), "Ok", "NieOk")[301:400]
#info$`0`[401:500] <- ifelse(as.numeric(info$nb) >= 350, "Ok", "NieOk")[401:500]
#info$`0`[501:616] <- ifelse(as.numeric(info$nb) >= 450, "Ok", "NieOk")[501:616]

rownames(info) <- NULL

#wersja 2
info$`0` <- ifelse(abs(as.numeric(info$nb) - as.numeric(info$`1:616`)) <= 200, "Ok", "NieOk")
sum(info$`0` == "Ok")/length(nb)
#wersja3
info$`1:616` <- abs(as.numeric(info$nb) - as.numeric(info$`1:616`))

mean(info$`1:616`)
summary(info$`1:616`)

info
